import * as core from '@actions/core';
import * as github from '@actions/github';
import { LLMResponse } from './llm-suggester';

export const SUGGESTIONS_INTRO = 'Thanks for the PR! Here are a few doc tweaks to improve integration and platform understanding for customers.';
export const NO_SUGGESTIONS_INTRO = "Thanks for the PR! I looked over the changes and didn't spot any doc updates needed to help customers integrate or understand the platform.";

/**
 * Format suggestions as markdown comment
 */
export function formatComment(response: LLMResponse): string {
  if (response.impact_level === 'none' || response.suggestions.length === 0) {
    return `## 📚 Documentation Check-In

${response.comment_intro?.trim() || NO_SUGGESTIONS_INTRO}

${response.summary}

Want me to focus on something specific next time? Add a \`prompt_instruction\` input to the workflow and I'll tailor the review.`;
  }

  const severityEmoji = {
    info: 'ℹ️',
    warning: '⚠️',
    critical: '🚨'
  };

  const suggestionBlocks = response.suggestions.map((s, i) => {
    const emoji = severityEmoji[s.severity];
    const lineInfo = s.start_line && s.end_line
      ? ` (lines ${s.start_line}-${s.end_line})`
      : '';

    return `### ${emoji} Suggestion ${i + 1}: ${s.type} \`${s.target_file}\`${lineInfo}

**Focus**: ${s.target_section}
**Why this helps**: ${s.rationale}

<details>
<summary>Suggested wording</summary>

\`\`\`markdown
${s.suggested_text}
\`\`\`

</details>`;
  }).join('\n\n');

  return `## 📚 Documentation Check-In

${response.comment_intro?.trim() || SUGGESTIONS_INTRO}

**Impact**: ${response.impact_level.toUpperCase()} | **Suggestions**: ${response.suggestions.length}

${suggestionBlocks}

---

Want me to lean into a particular style or audience? Add a \`prompt_instruction\` input in the workflow and I'll follow it on the next run.

<sub>🤖 Generated by [Soyio Docs Bot](https://github.com/soyio/soyio-docs-bot)</sub>`;
}

/**
 * Post comment to PR
 */
export async function postComment(
  token: string,
  owner: string,
  repo: string,
  prNumber: number,
  comment: string
): Promise<void> {
  const octokit = github.getOctokit(token);

  // Check if bot already commented
  const { data: comments } = await octokit.rest.issues.listComments({
    owner,
    repo,
    issue_number: prNumber
  });

  const botComment = comments.find(c =>
    c.body?.includes('📚 Documentation Check-In') ||
    c.body?.includes('Documentation Update Suggestions') ||
    c.body?.includes('Documentation Analysis')
  );

  if (botComment) {
    // Update existing comment
    await octokit.rest.issues.updateComment({
      owner,
      repo,
      comment_id: botComment.id,
      body: comment
    });
    core.info('Updated existing comment');
  } else {
    // Create new comment
    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body: comment
    });
    core.info('Posted new comment');
  }
}
